### PR TITLE
"No restart" option to ossec_ruleset.py

### PR DESCRIPTION
**Pull request by netflash**
I need this option for docker container. Probably one could need this for some other purposes.

### CODE REVIEW

**Comment by jesuslinares** [comment]
Hi, thanks for your contributions. That option it was in my ToDo list. Could you send the pull request to the development branch?. We use the master branch just for releases.

**Comment by netflash** [comment]
@jesuslinares Hi, sure.

BTW does this ToDo list published anywhere ?

**Comment by jesuslinares** [comment]
We are working in a new update. Then, maybe we publish the ToDo list, if it is necessary. Thanks.

**Comment by netflash** [comment]
@jesuslinares I think to have a public TODO would be more convenient to everyone.
maybe someone out of your company could work with some tasks, etc.

**Comment by jesuslinares** [comment]
@netflash usually it is a list of ideas, not a list of requirements. Anyway, you are right, we'll think about it.

**Pull request closed without merging**
