### PR TITLE
Create new CIS files for SLES 11 and 12

### PR DESCRIPTION
**Pull request by Joeri-MS**
Add new CIS files for sles 11 and sles 12.

### CODE REVIEW

**Comment by jesuslinares** [comment]
Hi Joeri-MS,

It looks pretty nice, I'm going to test it and it will be included.

It works only for SLES 11, right?. 

> f:/etc/os-release -> r:^PRETTY_NAME="SUSE Linux Enterprise Server 11";
> f:/etc/os-release -> r:^PRETTY_NAME="SUSE Linux Enterprise Server 11 SP1";
> f:/etc/os-release -> r:^PRETTY_NAME="SUSE Linux Enterprise Server 11 SP2";
> f:/etc/os-release -> r:^PRETTY_NAME="SUSE Linux Enterprise Server 11 SP3";
> f:/etc/os-release -> r:^PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4";

Thanks for your contribution, community is what makes OSSEC really great!.

**Comment by jesuslinares** [comment]
I tested it in Suse 11 and it works properly.
Thanks a lot!

**Comment by Joeri-MS** [comment]
The second file is for SLES 12.
They are stright forward ports from the RHEL CIS Files, fixed the CIS Numbers.

**Comment by jesuslinares** [comment]
My bad. I didn't see the second file. It will be included too.
Thanks!.

**Pull request merged**
